openapi: 3.0.0
info:
  title: API Catways - Port de Russell
  version: "1.0"
  description: API REST privée pour la gestion des catways et réservations

servers:
  - url: http://localhost:5000

paths:
  /login:
    post:
      summary: Connexion utilisateur
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Authentification réussie

  /users:
    get:
      summary: Liste tous les utilisateurs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des utilisateurs

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
